// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

#if USE_FB_TABLE

namespace ProtoTable
{

using global::System;
using global::FlatBuffers;

public class AdventurePassBuyLevelTable : IFlatbufferObject
{
public enum eCrypt : int
{
 code = -51098687,
};

  private Table __p = new Table();
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static AdventurePassBuyLevelTable GetRootAsAdventurePassBuyLevelTable(ByteBuffer _bb) { return GetRootAsAdventurePassBuyLevelTable(_bb, new AdventurePassBuyLevelTable()); }
  public static AdventurePassBuyLevelTable GetRootAsAdventurePassBuyLevelTable(ByteBuffer _bb, AdventurePassBuyLevelTable obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public AdventurePassBuyLevelTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int ID { get { int o = __p.__offset(4); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public int PointCost { get { int o = __p.__offset(6); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }

  public static Offset<AdventurePassBuyLevelTable> CreateAdventurePassBuyLevelTable(FlatBufferBuilder builder,
      int ID = 0,
      int PointCost = 0) {
    builder.StartObject(2);
    AdventurePassBuyLevelTable.AddPointCost(builder, PointCost);
    AdventurePassBuyLevelTable.AddID(builder, ID);
    return AdventurePassBuyLevelTable.EndAdventurePassBuyLevelTable(builder);
  }

  public static void StartAdventurePassBuyLevelTable(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddID(FlatBufferBuilder builder, int ID) { builder.AddInt(0, ID, 0); }
  public static void AddPointCost(FlatBufferBuilder builder, int PointCost) { builder.AddInt(1, PointCost, 0); }
  public static Offset<AdventurePassBuyLevelTable> EndAdventurePassBuyLevelTable(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<AdventurePassBuyLevelTable>(o);
  }
  public static void FinishAdventurePassBuyLevelTableBuffer(FlatBufferBuilder builder, Offset<AdventurePassBuyLevelTable> offset) { builder.Finish(offset.Value); }
};


}


#endif

