// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

#if USE_FB_TABLE

namespace ProtoTable
{

using global::System;
using global::FlatBuffers;

public class AppraisalProbabilityTable : IFlatbufferObject
{
public enum eCrypt : int
{
 code = 1737830770,
};

  private Table __p = new Table();
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static AppraisalProbabilityTable GetRootAsAppraisalProbabilityTable(ByteBuffer _bb) { return GetRootAsAppraisalProbabilityTable(_bb, new AppraisalProbabilityTable()); }
  public static AppraisalProbabilityTable GetRootAsAppraisalProbabilityTable(ByteBuffer _bb, AppraisalProbabilityTable obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public AppraisalProbabilityTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int ID { get { int o = __p.__offset(4); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public string section { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : FlatBufferConstants.DefaultString; } }
  public ArraySegment<byte>? GetSectionBytes() { return __p.__vector_as_arraysegment(6); }
  public string weight { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : FlatBufferConstants.DefaultString; } }
  public ArraySegment<byte>? GetWeightBytes() { return __p.__vector_as_arraysegment(8); }

  public static Offset<AppraisalProbabilityTable> CreateAppraisalProbabilityTable(FlatBufferBuilder builder,
      int ID = 0,
      StringOffset sectionOffset = default(StringOffset),
      StringOffset weightOffset = default(StringOffset)) {
    builder.StartObject(3);
    AppraisalProbabilityTable.AddWeight(builder, weightOffset);
    AppraisalProbabilityTable.AddSection(builder, sectionOffset);
    AppraisalProbabilityTable.AddID(builder, ID);
    return AppraisalProbabilityTable.EndAppraisalProbabilityTable(builder);
  }

  public static void StartAppraisalProbabilityTable(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddID(FlatBufferBuilder builder, int ID) { builder.AddInt(0, ID, 0); }
  public static void AddSection(FlatBufferBuilder builder, StringOffset sectionOffset) { builder.AddOffset(1, sectionOffset.Value, 0); }
  public static void AddWeight(FlatBufferBuilder builder, StringOffset weightOffset) { builder.AddOffset(2, weightOffset.Value, 0); }
  public static Offset<AppraisalProbabilityTable> EndAppraisalProbabilityTable(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<AppraisalProbabilityTable>(o);
  }
  public static void FinishAppraisalProbabilityTableBuffer(FlatBufferBuilder builder, Offset<AppraisalProbabilityTable> offset) { builder.Finish(offset.Value); }
};


}


#endif

