// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

#if USE_FB_TABLE

namespace ProtoTable
{

using global::System;
using global::FlatBuffers;

public class ChiJiRegionTable : IFlatbufferObject
{
public enum eCrypt : int
{
 code = 2099043363,
};

  private Table __p = new Table();
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ChiJiRegionTable GetRootAsChiJiRegionTable(ByteBuffer _bb) { return GetRootAsChiJiRegionTable(_bb, new ChiJiRegionTable()); }
  public static ChiJiRegionTable GetRootAsChiJiRegionTable(ByteBuffer _bb, ChiJiRegionTable obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ChiJiRegionTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int ID { get { int o = __p.__offset(4); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public string regionName { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : FlatBufferConstants.DefaultString; } }
  public ArraySegment<byte>? GetRegionNameBytes() { return __p.__vector_as_arraysegment(6); }
  public string regionDescribe { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : FlatBufferConstants.DefaultString; } }
  public ArraySegment<byte>? GetRegionDescribeBytes() { return __p.__vector_as_arraysegment(8); }

  public static Offset<ChiJiRegionTable> CreateChiJiRegionTable(FlatBufferBuilder builder,
      int ID = 0,
      StringOffset regionNameOffset = default(StringOffset),
      StringOffset regionDescribeOffset = default(StringOffset)) {
    builder.StartObject(3);
    ChiJiRegionTable.AddRegionDescribe(builder, regionDescribeOffset);
    ChiJiRegionTable.AddRegionName(builder, regionNameOffset);
    ChiJiRegionTable.AddID(builder, ID);
    return ChiJiRegionTable.EndChiJiRegionTable(builder);
  }

  public static void StartChiJiRegionTable(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddID(FlatBufferBuilder builder, int ID) { builder.AddInt(0, ID, 0); }
  public static void AddRegionName(FlatBufferBuilder builder, StringOffset regionNameOffset) { builder.AddOffset(1, regionNameOffset.Value, 0); }
  public static void AddRegionDescribe(FlatBufferBuilder builder, StringOffset regionDescribeOffset) { builder.AddOffset(2, regionDescribeOffset.Value, 0); }
  public static Offset<ChiJiRegionTable> EndChiJiRegionTable(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ChiJiRegionTable>(o);
  }
  public static void FinishChiJiRegionTableBuffer(FlatBufferBuilder builder, Offset<ChiJiRegionTable> offset) { builder.Finish(offset.Value); }
};


}


#endif

