// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

#if USE_FB_TABLE

namespace ProtoTable
{

using global::System;
using global::FlatBuffers;

public class EquipHandbookCommentTable : IFlatbufferObject
{
public enum eCrypt : int
{
 code = -249624373,
};

  private Table __p = new Table();
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static EquipHandbookCommentTable GetRootAsEquipHandbookCommentTable(ByteBuffer _bb) { return GetRootAsEquipHandbookCommentTable(_bb, new EquipHandbookCommentTable()); }
  public static EquipHandbookCommentTable GetRootAsEquipHandbookCommentTable(ByteBuffer _bb, EquipHandbookCommentTable obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public EquipHandbookCommentTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int ID { get { int o = __p.__offset(4); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : FlatBufferConstants.DefaultString; } }
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
  public int SortOrder { get { int o = __p.__offset(8); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public string Comment { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : FlatBufferConstants.DefaultString; } }
  public ArraySegment<byte>? GetCommentBytes() { return __p.__vector_as_arraysegment(10); }

  public static Offset<EquipHandbookCommentTable> CreateEquipHandbookCommentTable(FlatBufferBuilder builder,
      int ID = 0,
      StringOffset NameOffset = default(StringOffset),
      int SortOrder = 0,
      StringOffset CommentOffset = default(StringOffset)) {
    builder.StartObject(4);
    EquipHandbookCommentTable.AddComment(builder, CommentOffset);
    EquipHandbookCommentTable.AddSortOrder(builder, SortOrder);
    EquipHandbookCommentTable.AddName(builder, NameOffset);
    EquipHandbookCommentTable.AddID(builder, ID);
    return EquipHandbookCommentTable.EndEquipHandbookCommentTable(builder);
  }

  public static void StartEquipHandbookCommentTable(FlatBufferBuilder builder) { builder.StartObject(4); }
  public static void AddID(FlatBufferBuilder builder, int ID) { builder.AddInt(0, ID, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset NameOffset) { builder.AddOffset(1, NameOffset.Value, 0); }
  public static void AddSortOrder(FlatBufferBuilder builder, int SortOrder) { builder.AddInt(2, SortOrder, 0); }
  public static void AddComment(FlatBufferBuilder builder, StringOffset CommentOffset) { builder.AddOffset(3, CommentOffset.Value, 0); }
  public static Offset<EquipHandbookCommentTable> EndEquipHandbookCommentTable(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<EquipHandbookCommentTable>(o);
  }
  public static void FinishEquipHandbookCommentTableBuffer(FlatBufferBuilder builder, Offset<EquipHandbookCommentTable> offset) { builder.Finish(offset.Value); }
};


}


#endif

