// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

#if USE_FB_TABLE

namespace ProtoTable
{

using global::System;
using global::FlatBuffers;

public class MainlandTable : IFlatbufferObject
{
public enum eCrypt : int
{
 code = -981910982,
};

  private Table __p = new Table();
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static MainlandTable GetRootAsMainlandTable(ByteBuffer _bb) { return GetRootAsMainlandTable(_bb, new MainlandTable()); }
  public static MainlandTable GetRootAsMainlandTable(ByteBuffer _bb, MainlandTable obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public MainlandTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int ID { get { int o = __p.__offset(4); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : FlatBufferConstants.DefaultString; } }
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
  public int AreaIDsArray(int j) { int o = __p.__offset(8); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int AreaIDsLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ArraySegment<byte>? GetAreaIDsBytes() { return __p.__vector_as_arraysegment(8); }
 private FlatBufferArray<int> AreaIDsValue;
 public FlatBufferArray<int>  AreaIDs
 {
  get{
  if (AreaIDsValue == null)
  {
    AreaIDsValue = new FlatBufferArray<int>(this.AreaIDsArray, this.AreaIDsLength);
  }
  return AreaIDsValue;}
 }

  public static Offset<MainlandTable> CreateMainlandTable(FlatBufferBuilder builder,
      int ID = 0,
      StringOffset NameOffset = default(StringOffset),
      VectorOffset AreaIDsOffset = default(VectorOffset)) {
    builder.StartObject(3);
    MainlandTable.AddAreaIDs(builder, AreaIDsOffset);
    MainlandTable.AddName(builder, NameOffset);
    MainlandTable.AddID(builder, ID);
    return MainlandTable.EndMainlandTable(builder);
  }

  public static void StartMainlandTable(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddID(FlatBufferBuilder builder, int ID) { builder.AddInt(0, ID, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset NameOffset) { builder.AddOffset(1, NameOffset.Value, 0); }
  public static void AddAreaIDs(FlatBufferBuilder builder, VectorOffset AreaIDsOffset) { builder.AddOffset(2, AreaIDsOffset.Value, 0); }
  public static VectorOffset CreateAreaIDsVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static void StartAreaIDsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<MainlandTable> EndMainlandTable(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<MainlandTable>(o);
  }
  public static void FinishMainlandTableBuffer(FlatBufferBuilder builder, Offset<MainlandTable> offset) { builder.Finish(offset.Value); }
};


}


#endif

