// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

#if USE_FB_TABLE

namespace ProtoTable
{

using global::System;
using global::FlatBuffers;

public class StandardNormalDistributionTable : IFlatbufferObject
{
public enum eCrypt : int
{
 code = -1196071976,
};

  private Table __p = new Table();
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static StandardNormalDistributionTable GetRootAsStandardNormalDistributionTable(ByteBuffer _bb) { return GetRootAsStandardNormalDistributionTable(_bb, new StandardNormalDistributionTable()); }
  public static StandardNormalDistributionTable GetRootAsStandardNormalDistributionTable(ByteBuffer _bb, StandardNormalDistributionTable obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public StandardNormalDistributionTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int ID { get { int o = __p.__offset(4); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public int InputValue { get { int o = __p.__offset(6); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public int OutputValue { get { int o = __p.__offset(8); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }

  public static Offset<StandardNormalDistributionTable> CreateStandardNormalDistributionTable(FlatBufferBuilder builder,
      int ID = 0,
      int InputValue = 0,
      int OutputValue = 0) {
    builder.StartObject(3);
    StandardNormalDistributionTable.AddOutputValue(builder, OutputValue);
    StandardNormalDistributionTable.AddInputValue(builder, InputValue);
    StandardNormalDistributionTable.AddID(builder, ID);
    return StandardNormalDistributionTable.EndStandardNormalDistributionTable(builder);
  }

  public static void StartStandardNormalDistributionTable(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddID(FlatBufferBuilder builder, int ID) { builder.AddInt(0, ID, 0); }
  public static void AddInputValue(FlatBufferBuilder builder, int InputValue) { builder.AddInt(1, InputValue, 0); }
  public static void AddOutputValue(FlatBufferBuilder builder, int OutputValue) { builder.AddInt(2, OutputValue, 0); }
  public static Offset<StandardNormalDistributionTable> EndStandardNormalDistributionTable(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<StandardNormalDistributionTable>(o);
  }
  public static void FinishStandardNormalDistributionTableBuffer(FlatBufferBuilder builder, Offset<StandardNormalDistributionTable> offset) { builder.Finish(offset.Value); }
};


}


#endif

